Homework0
Vasilisa05/itc-frontend pull request #2
Opened 2018-03-16 11:08 UTC by Vasilisa05

2018-03-16 16:43 UTC, mlshv commented
Прочитай частые ошибки пожалуйста

2018-03-18 08:40 UTC, mlshv requested changes
у тебя тут на 22 балла. можешь доделать эту либо оставить и сделать следующую

2018-03-18 08:40 UTC, mlshv commented on my_hometask.html
> +
не понял

что это за файл?

2018-03-18 08:40 UTC, mlshv commented on my_hometask2.html
> +            return (arr1.concat(arr2));
return это не функция, btw. в телеграфе было

2018-03-18 08:40 UTC, mlshv commented on my_hometask2.html
> +            for (i = 0; i < arguments.length; i++) {
прочти частые ошибки

2018-03-18 10:54 UTC, Vasilisa05 commented on my_hometask.html
> +
Это неудачная попытка залить, а как удалить, не знаю

2018-03-18 10:56 UTC, Vasilisa05 commented on my_hometask2.html
> +            for (i = 0; i < arguments.length; i++) {
Я читала, уже подправляла, не знаю, что не так 
Вечером вторую скину)

2018-03-18 10:57 UTC, Vasilisa05 commented on my_hometask2.html
> +            return (arr1.concat(arr2));
А через что здесь писать?

2018-03-21 09:58 UTC, mlshv commented on my_hometask2.html
> +            for (i = 0; i < arguments.length; i++) {
Значит прочти ещё раз

2018-03-21 09:59 UTC, mlshv commented on my_hometask2.html
> +            return (arr1.concat(arr2));
без скобок

2018-03-21 10:00 UTC, mlshv commented
Вливаю вместе с первой

2018-03-21 10:00 UTC, merged